version: '3.8'

services:
  app:
    build: .
    container_name: questao-certa-app
    ports:
      - "8080:8080"
    volumes:
      - .:/home/go/app
    environment:
      PORT: ${PORT}
      DEVELOPMENT: ${DEVELOPMENT}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_COLLECTION: ${MONGODB_COLLECTION}
      MONGODB_COLLECTION_USER: ${MONGODB_COLLECTION_USER}
      MONGODB_NAME: ${MONGODB_NAME}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_ATLAS_PASSWORD: ${MONGODB_ATLAS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0.2-jammy
    container_name: questao-certa-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  postgres:
    image: postgres:16.0-alpine3.18
    container_name: questao-certa-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  air:
    image: cosmtrek/air:v1.45.0
    container_name: questao-certa-air
    ports:
      - "8180:8080"
    volumes:
      - .:/home/go/app
    working_dir: /home/go/app
    command: [ "air", "-c", ".air.toml" ]
