// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package bridge

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	Name      string
	Email     string
	Password  string
	Admin     bool
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
