version: '3.8'

services:
  app:
    image: questao-certa:latest
    container_name: questao-certa
    environment:
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
  mongodb:
    image: mongo:latest
    container_name: questao-certa-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
